# Generated by Django 6.0.1 on 2026-02-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('work_start_time', models.TimeField(help_text='Expected check-in time')),
                ('work_end_time', models.TimeField(help_text='Expected check-out time')),
                ('grace_period_minutes', models.PositiveIntegerField(default=5, help_text='Minutes after work_start_time before considered late')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_person_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_id'],
            },
        ),
    ]
