# Generated by Django 6.0.1 on 2026-02-14 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('work_start_time', models.TimeField(verbose_name='Ish boshlanish vaqti')),
                ('work_end_time', models.TimeField(verbose_name='Ish tugash vaqti')),
                ('grace_period_minutes', models.PositiveIntegerField(default=5, help_text='Ish boshlanish vaqtidan keyin shuncha daqiqa kechikishga ruxsat', verbose_name='Ruxsat etilgan muhlat (daqika)')),
                ('working_days', models.CharField(default='0,1,2,3,4', help_text='Ish kunlari: vergul bilan ajratilgan (0=Du, 1=Se, 2=Ch, 3=Pa, 4=Ju, 5=Sh, 6=Ya). Masalan 0,1,2,3,4 = Du-Ju', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ish grafigi',
                'verbose_name_plural': 'Ish grafiklari',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Ruxsat etilgan muhlat daqiqada (grafik tanlanmasa ishlatiladi)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(help_text='Ish tugash (grafik tanlanmasa ishlatiladi)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(help_text='Ish boshlanish (grafik tanlanmasa ishlatiladi)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.workschedule', verbose_name='Ish grafigi'),
        ),
    ]
