# Generated by Django 6.0.1 on 2026-02-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username (ixtiyoriy)'),
        ),
    ]
