# Generated by Django 6.0.1 on 2026-02-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_telegram_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='working_days',
            field=models.CharField(default='0,1,2,3,4', help_text='Ish kunlari: vergul bilan ajratilgan (0=Du..6=Ya). Masalan 0,1,2,3,4 = Du-Ju', max_length=20),
        ),
    ]
