# Generated by Django 6.0.1 on 2026-02-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyrule',
            name='max_amount_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=50000, help_text="Bir xodim uchun shu kundagi jami jarima shu summandan oshmasin. Bo'sh qoldirilsa cheklov yo'q.", max_digits=10, null=True, verbose_name="Kunlik maksimum (so'm)"),
        ),
        migrations.AlterField(
            model_name='penaltyrule',
            name='rule_type',
            field=models.CharField(choices=[('per_minute', 'Har daqiqaga'), ('fixed', "Qat'iy summa"), ('custom', 'Boshqa')], default='per_minute', max_length=20),
        ),
    ]
