# Generated by Django 6.0.1 on 2026-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0002_add_max_amount_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='penalty_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Jarima foizi (%)'),
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='percent_if_late_gt_threshold',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Kechikish chegaradan oshsa (masalan 2 = 2%).', max_digits=5, verbose_name='Foiz (> chegara)'),
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='percent_if_late_le_threshold',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Kechikish chegara daqiqagacha bo'lsa (masalan 1 = 1%).", max_digits=5, verbose_name='Foiz (≤ chegara)'),
        ),
        migrations.AddField(
            model_name='penaltyrule',
            name='threshold_minutes',
            field=models.PositiveIntegerField(default=30, help_text="Oylikdan foiz: shu daqiqagacha birinchi foiz, undan keyin ikkinchi foiz qo'llanadi.", verbose_name='Chegara (daq)'),
        ),
        migrations.AlterField(
            model_name='penaltyrule',
            name='amount_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Per minute (per_minute) or fixed amount (fixed). Oylikdan foiz uchun ishlatilmaydi.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='penaltyrule',
            name='rule_type',
            field=models.CharField(choices=[('per_minute', 'Har daqiqaga'), ('fixed', "Qat'iy summa"), ('percent_of_salary', 'Oylikdan foiz'), ('custom', 'Boshqa')], default='per_minute', max_length=20),
        ),
    ]
