# Generated by Django 6.0.1 on 2026-02-21 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0003_add_percent_of_salary_rule_and_penalty_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='penalty_date',
            field=models.DateField(default=datetime.date.today, help_text="Jarima qaysi kun uchun (davomat o'tgan sana).", verbose_name='Jarima sanasi'),
        ),
    ]
