# Generated by Django 6.0.1 on 2026-02-21 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_penalty_exemption'),
        ('penalties', '0005_backfill_penalty_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-penalty_date', '-created_at'], 'verbose_name': 'Penalty', 'verbose_name_plural': 'Penalties'},
        ),
        migrations.CreateModel(
            name='PenaltyExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Dan')),
                ('date_to', models.DateField(help_text='Bir kun uchun Dan = Gacha qiling.', verbose_name='Gacha')),
                ('reason_type', models.CharField(choices=[('sick_leave', 'Kasallik (bolnich)'), ('leave_approved', 'Ishdan ruxsat tasdiqlangan'), ('business_trip', 'Ish safari'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Sabab')),
                ('reason_text', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalty_exemptions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_exemptions', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Jarimadan ozod',
                'verbose_name_plural': 'Jarimadan ozodlar',
                'ordering': ['-date_from'],
            },
        ),
    ]
