# Generated by Django 6.0.1 on 2026-04-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0006_add_penalty_exemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyrule',
            name='department',
            field=models.CharField(blank=True, help_text="Bo'sh qoldiring — barcha bo'limlar uchun umumiy qoida. To'ldiring — faqat shu nomdagi bo'lim (xodim kartasidagi bo'lim bilan mos kelishi kerak). Bir vaqtda bir bo'lim uchun bitta faol qoida.", max_length=100, null=True, verbose_name="Bo'lim"),
        ),
    ]
