# Generated by Django 5.2.12 on 2026-04-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0004_add_penalty_exemption'),
        ('penalties', '0007_add_penalty_rule_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('decision', models.CharField(choices=[('created', 'Yaratildi'), ('skipped', "O'tkazib yuborildi"), ('error', 'Xatolik')], db_index=True, max_length=20)),
                ('reason_code', models.CharField(db_index=True, max_length=64)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_decision_logs', to='employees.employee')),
                ('lateness_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='attendance.latenessrecord')),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='penalties.penalty')),
            ],
            options={
                'verbose_name': 'Jarima qaror logi',
                'verbose_name_plural': 'Jarima qaror loglari',
                'ordering': ['-created_at'],
            },
        ),
    ]
