# Generated by Django 6.0.1 on 2026-02-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(blank=True, max_length=50)),
                ('api_username', models.CharField(blank=True, max_length=100)),
                ('api_password', models.CharField(blank=True, max_length=255)),
                ('webhook_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Settings',
                'verbose_name_plural': 'Integration Settings',
            },
        ),
    ]
