# Generated by Django 6.0.1 on 2026-02-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
