# Generated by Django 5.2.12 on 2026-04-15 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_add_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('device_ip', models.CharField(blank=True, max_length=64)),
                ('external_event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payload_json', models.JSONField(default=dict)),
                ('event_time_device', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('unmatched', 'Unmatched'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Raw Device Event',
                'verbose_name_plural': 'Raw Device Events',
                'ordering': ['-received_at'],
            },
        ),
    ]
